version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Topic: dependencies"
      - "Priority: soon"
    commit-message:
      prefix: cargo
    cooldown:
      default-days: 14
      semver-patch-days: 0
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Topic: dependencies"
      - "Priority: soon"
    commit-message:
      prefix: ci
