[package]
name = "repology_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
sqlx = { version = "0.8.0", default-features = false }
strum = { version = "0.26.3", features = ["strum_macros"] }
strum_macros = "0.26.4"
